log
{
  default_level INFO
}
tables
{
  cs_max_packets 65536
}
face_system
{
  unix
  {
    path /run/nfd/nfd.sock
  }
  udp
  {
    port 6363
  }
  ether
  {
    mcast yes
  }
}
authorizations
{
  authorize
  {
    certfile any
    privileges
    {
      faces
      fib
      cs
      strategy-choice
    }
  }
}
rib
{
  localhost_security
  {
    rule
    {
      id "any-interaction"
      for interest
      filter
      {
        type name
        regex ^<>*$
      }
      checker
      {
        type customized
        sig-type rsa-sha256
        key-locator
        {
          type name
          regex ^<>*$
        }
      }
    }
    trust-anchor
    {
      type any
    }
  }
}
